id: CELoss
type: CELoss
_target_: aucurriculum.curricula.scoring.CELoss
run_name: CIFAR-100_WideResNet-28-4_SAM_0.1_128_epoch_200_CosineAnnealingLR_CIFAR100-aug_N_N_None_None_1_0_11
criterion: autrainer.criterions.CrossEntropyLoss
stop: best # "best" or "last"
subset: train # train, dev, test
