id: ProbabilityScore
type: ProbabilityScore
_target_: probability_score.ProbabilityScore
stop: last # "best" or "last"
subset: train # train, dev, test

run_name: CIFAR-10_EfficientNet-B0_Adam_0.001_128_epoch_100_None_None_N_N_None_None_1_0_42 # has to be defined based on a finished run
